// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ListSounds() {
  return window['go']['main']['App']['ListSounds']();
}

export function ListWallpapers() {
  return window['go']['main']['App']['ListWallpapers']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
