// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function HideWindow():Promise<void>;

export function ListSounds():Promise<Array<main.CategoryInfo>>;

export function ListWallpapers():Promise<Array<main.WallpaperInfo>>;

export function QuitApp():Promise<void>;

export function ShowWindow():Promise<void>;
